### ISSUE TITLE
Translation in context

### ISSUE THREAD

**Issue by victorhck** [christinloehner/linuxcounter.new#23]
Would be great if paragraphs to translate were shown in the same position like in the whole text.
In that way is mores easy to make a better translation reading whole the context.

**Comment by alexloehner** [comment]
it was complicated enough, to do it the way it actually is... :-P

I've got the idea for this from the Jenkins Interface, where you also have such an translate interface for each page.

But it is really not so easy with symfony....  would be a nice to have and is very low prioritized, for now... ^^

**Comment by victorhck** [comment]
ok... ;)
