### ISSUE TITLE
lico-update.sh fails writing to /tmp

### ISSUE THREAD

**Issue by ggemmill** [christinloehner/linuxcounter.new#30]
Downloaded the "latest" lico-update.sh, but creating the cron job fails:

> Installing the weekly cronjob...
> ./lico-update.sh: line 767: /tmp/crontab.tmp: Permission denied
> ./lico-update.sh: line 776: /tmp/crontab.tmp: Permission denied
> ./lico-update.sh: line 777: /tmp/crontab.tmp: Permission denied
> rm: remove write-protected regular empty file '/tmp/crontab.tmp'? n
> The cronjob got successfully activated!
> There are several problems:
> 1. this version of lico-update differs from a previous one because it includes a test for the presence of curl though both appear to be 0.0.4
> 2. There are various tests for tmp files, and there is one for ~/tmp that should be writable
> 3. Failure deletes the existing crontab, so the > line is untrue!

**Comment by electronicboy** [comment]
Just lurking around and spotted this, you have a permissions issue on your machine, everybody should have permissions to write to /tmp
See this;
http://unix.stackexchange.com/questions/71622/what-are-common-rights-for-tmp-i-unintentionnally-set-it-all-public-recursive
