### ISSUE TITLE
lico-update.sh script error

### ISSUE THREAD

**Issue by slsimic** [christinloehner/linuxcounter.new#54]
when executing update script in console when scanning for system configuration error is shown
/usr/local/bin/lico-update.sh: line 616: [: : integer expression expected

**Comment by GittyUpTom** [comment]
Which version of the update script are you using?
I can't see an expression test on line 616 of either version 0.0.4 or 0.3.20
In fact, the version on the download page is older than the one I am using now.
So, I think the newest version should be advertised.

**Comment by christinloehner** [comment]
this should be fixed since some months (years?)
