### ISSUE TITLE
Member profile information has been lost, no state field, and other fields don't match the corresponding description.

### ISSUE THREAD

**Issue by tallship** [christinloehner/linuxcounter.new#68]
After logging in I noticed that my profile information is all blank - no ICQ, jabber, Skype, etc., info, or my location - it's all empty. I input all of this information again but it won't let me put back in the year that I've been using Linux since, without also providing a month and day (BTW, it's 1992).

There's also no field for the state in which I reside (California).

Finally, the fields are off by one - i.e., website appears not to have an entry at all, but in reality all of the respective fields are in fact one field before the description of that field.

Here is a screenie of what that looks like:
http://content.screencast.com/users/NorthTech.US/folders/Jing/media/9fb047cc-3fc6-4de2-bd95-bdb8693168bb/2016-03-24_1936.png

I've also included a copy of that screenie as an attachment to this bug report.

Thank you in advance for your attention to this matter.
![2016-03-24_1936](https://cloud.githubusercontent.com/assets/561994/14036691/ea5a1ed4-f1f8-11e5-922a-8faf3f18ea7b.png)

**Comment by LennyNer0** [comment]
Yes, I just wanted to put in year only, as TBH I cant really remember.

**Comment by tallship** [comment]
Okay now!

Thank you so much @Nikolice , It took my updates and placed them into my public profile just fine!

https://www.linuxcounter.net/user/190795

A little clunky, meaning that if you try to enter anything invalid it won't pick it up, like attempting to just put in the year. You have to put in the month and day along with the year or it will be rejected. I remember the month in 1992 when, as one of the earliest ISPs in Los Angeles, I started migrating from using 386BSD to SLS (June), so I just put in my daughter's birthday of the 19th (I probably started adopting it about two weeks earlier though). My daughter wasn't actually born for 3 more years, by the way ;)

After that, we based the Personal Internet Stations (Litterally plug and play hardware workstations with their own pre-configured IP addresses from my personal network blocks issued by nic.ddn.mil). All a customer had to do was plug in the brand new 486 based computers we manufactured and turn it on - from there it would automatically dial up our point of presence as a regular host node via a "nailed up" (24/7) SLIP connection.

These machines ran either Linboard LiGNUx, a distro I refactored from SLS, and later we began shipping them with Ygdrassil. Linboard LiGNUx  was also available in brick and mortar retail stores like Computerland and Egghead Software stores. A few months later, I discovered Slackware, and eventually began to abandon Linboard in favor of Slackware for pretty much everything (Volkerdi did a much better job and my maintenance work on Linboard sucked in comparison).

If possible, I would like to see more fields to accommodate github and Linkedin, since those are such prominent entities in this day and age, but I don't know if you could do a pull request involving those database updates.

An Interesting note is that Faceplant and G+ profiles are rendered on the public profile page as actual links, but not twatter or Identi.ca - so maybe that's something that you could place on the roadmap?

Finally, The "Interests" and "Hobbies" sections are woefully inadequate in their formatting. Are basic HTML tags supported in those fields?

![2018-05-01_2033-linux_counter](https://user-images.githubusercontent.com/561994/39504318-9182b958-4d7f-11e8-9656-6e419c7ea432.png)

Thank you once again, The Linux Counter is not just an important historical component of computing history, but rather, a relevant and significant resource for the GNU/Linux and FOSS communities in General. I guess it's time for me to put out some more plugs for it in blogs, huh?

Kindest regards,

Bradley

**Comment by christinloehner** [comment]
Hey Bradley, 

thanks a lot for your information! I've just tried to fix some things. So please take a look now. :-)  

Best regards 
Christin

**Comment by christinloehner** [comment]
Hey Bradley,

thanks a lot for your information! I've just tried to fix some things. So please take a look now. :-)

Best regards
Christin

**Comment by tallship** [comment]
Christin,

First, let me say, I had been wondering for some time where things were at. I've been with you as a bug reporter and proud member throughout the whole transcendence and handover of they keys to the car, it was ugly for a while, and the work you went through collecting and making sense of the hodgepodge of data from the old counter.li.org site is truly appreciated.

I had thought that this project had fallen into a dormant state again a couple of years ago, wondering how long the hiatus that I perceived would last on your part - That having been said, I also realized that this undertaking is a labor of love, and everyone needs to step back now and again.

I was especially elated when you migrated from Trac (Wasn't it?) to github, and....

Second, WOW! Awesome. The site/system/engine is everything I had hoped it would be once again in its modernized incarnation! And being a longtime stalwart Slacker, well, you gotta love that courier font ;)

Okay my report back on the updates: It's beautiful!

Here's what my public profile page looks like now:

![linux_counter-public_profile](https://user-images.githubusercontent.com/561994/39513244-936500fe-4da8-11e8-82e2-732d185f1ac7.png)


Oddities, inconsistencies: On the private profile page, some of the social media fields aren't showing up.

Here's a screeenie of that:
https://content.screencast.com/users/NorthTech.US/folders/Jing/media/fb6035e8-755e-492a-9a0b-5c67ca22f541/2018-05-02_0111.png

Personnally, I really don't care to bother about that, since only I can see it and other's see the public profile page. The only reason I go there is to pull a link to the badge or my API key anyway.

Finally, it's really good to see you in action again Christin, and thank you for all that you have contributed to the FOSS community! Now I suppose it's my turn again to promote the project with a couple of articles to bring some more traffic and registrations of refugees and new folks who wish to be included.

ah... one more thing. I did notice that it's just month and year now, which is much more practical 👍 

Kindest regards,

Bradley

**Comment by tallship** [comment]
Okay I think as the OP of this bugtrack report, I'm supposed to close this issue now?

It appears to me that all of the major issues have been addressed, and then some 🥇 

Thanks @Nikolice , thanks @christinloehner !!!

**Comment by christinloehner** [comment]
Hey Bradley,

first I want to thank you really very much for your warm words about the project and the revive of it. It was a really hard work, migrating the very old databases of counter.li.org into something useful.  :-P

I had a great timeout during the last two years and thus, I haven't done much at the new project. The reason was my transition of my males body into the body of a female, since I'm a transgender woman, as you may have noticed. In the end of january this year I had my first of two gender surgeries, the second and last one will happen in end of august.
![bildschirmfoto-von- 2017-12-14-06-34-48](https://user-images.githubusercontent.com/1255288/39514917-d2fd5d06-4df8-11e8-977c-9e739d55a6fd.png)


So, well... I'm back again and I will try to maintain the project now again as in the beginning. :-)

Thanks again!  :-*

best regards
Christin
