### ISSUE TITLE
Missing “Edit machines” link on “Account” menu

### ISSUE THREAD

**Issue by raffaellod** [christinloehner/linuxcounter.new#86]
I can’t seem to find a way to edit my (now outdated) machines. I understand now there’s a REST API for updates, but shouldn’t there still be a way to update machines manually?

**Comment by elbarbudo** [comment]
Just clicking on the machine's name brings an EDITABLE display of it.

**Comment by raffaellod** [comment]
The only place where I can see a list of my machines is Account > Show public profile, and if I click the name of one of my machines I’m taken to a non-editable page (e.g. https://www.linuxcounter.net/machine/409418).

**Comment by christinloehner** [comment]
@raffaellod when you login to your LiCo acount, you are on your profile page. Just scroll down, without using the navigation menu after login... just scroll down to the list of your machines and click one.
