### ISSUE TITLE
IDEAS for the New Linux Counter

### ISSUE THREAD

**Issue by christinloehner** [christinloehner/linuxcounter.new#9]
Here we can collect some ideas for the Linux Counter.
If you have any ideas, please don't hesitate to write a comment to this ticket.

**Comment by Translator5** [comment]
I've a idea, which is a bit hardly to create I think, but as far my knowledge it should be possible.

Yesterday I watched the "Linux Sucks 2014" and the maintainer showed there a diagram of user statistics of the popular distributions. He said he used the data of Distrowatch.

Yes Distrowatch is not bad, but really if you compare the website clicks on the homepage it didn't tell you more than just the click's. You can also compare it with the Windows hompage and see that this is a dramatically difference between the click's and real users.

In Linux Counter this is more difficult, you have to register... this a more limited way to get real statistics.

There is also a comparable way to use Google trends and compare this. There you can see the different interest's in Linux sorting by country and town. 

But remember Ubuntu is as far I know the only distribution which really do marketing.
LinuxMint manipulate the distrowatch by setting their homepage to the main-new tab of Firefox in their, and its allowed.

But here some fact's;
I know that there is every year a Linux Meeting in Berlin. Mostly OpenSuSe and RedHat\Fedora.
There is a new Linux development University in Moscow also they use Linux (RoSa) in shools and the government which highly support open source is tending to ALT Linux.
In Kuba there is a big community for Linux.
Czech republic, Taiwan, India and Italia are very interested in Linux if you listen to Google Trends.
In China there are some developing a Chinese \Russian Linux named Deepin.
USA where every distribution is been represented, Canada where Arch Linux come from...
And I just talk here about the desktop version.
So as soon as you read this you do not trust the statistics!

So but now to my Idea;
My Idea is a GPLv3 Linux software, which will automatically send statistics to Linux counter if the Computers is already up for at minimum 10 minutes. The statistics have to been send can be configurated by the user. If he or she wants to disable it they are free to do.
This software should have a GUI.
The data which should been sen once a day\week if the uptime will reach a specific member e.g. 10 or 30 minutes;
- Distribution
- Desktop environments
Optimal;
- Hardware
- Ammount of Users
- Software

**Comment by christinloehner** [comment]
Sorry for the late answer... this software already exists since the beginning of the new linuxcounter in 2011. It is the lico-update script. Just click on download on the linuxcounter page
